<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.16.2 by Michael Rose
  Copyright 2013-2019 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE
-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">

<!-- begin _includes/seo.html --><title>"Gautam Mittal"</title>
<meta name="description" content="Data Science Portfolio">



<meta property="og:type" content="website">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="Mumid Sharif Rony">
<meta property="og:title" content="Mumid Sharif Rony">
<meta property="og:url" content="https://Gautam-0.github.io/">




  <meta property="og:image" content="https://mumid.github.io/images/cover.jpg">









  

  


<link rel="canonical" href="https://mumid.github.io/">



  <link rel="next" href="https://mumid.github.io/page2/">

