title: "Gautam Mittal" # your name (or website title) here
logo: "/images/Chess.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Avid data enthusiast talented in data analysis, visualization, and predictive modeling. Expertise in Python, SQL, Power BI, and Excel. Good problem-solver, meticulous, and skilled at explaining complicated concepts. Fast learner, cooperative team player, and constant searcher for novel data applications to practical problems. Together, let's connect and unleash the power of data!
  <br><br>
  <a href="https://www.linkedin.com/in/gautammittal003//">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
